---
version: '3'

services:
  stackstate-agent:
    container_name: "splunk-trace-agent"
    image: "docker.io/stackstate/stackstate-agent-2-test:STAC-16164-splunk-QA"
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8126:8126"
    volumes:
      # - "./conf.d/agent_v2_integration_transactional_sample.d:/etc/stackstate-agent/conf.d/agent_v2_integration_transactional_sample.d"
      - "./conf.d/splunk_metric.d:/etc/stackstate-agent/conf.d/splunk_metric.d"
      - "./splunk_telemetry_base.py:/opt/stackstate-agent/embedded/lib/python2.7/site-packages/stackstate_checks/splunk/telemetry/splunk_telemetry_base.py"
      - "./splunk_metric.py:/opt/stackstate-agent/embedded/lib/python2.7/site-packages/stackstate_checks/splunk_metric/splunk_metric.py"
      - "./base.py:/opt/stackstate-agent/embedded/lib/python2.7/site-packages/stackstate_checks/base/checks/base.py"
      - "./splunk_client.py:/opt/stackstate-agent/embedded/lib/python2.7/site-packages/stackstate_checks/splunk/client/splunk_client.py"
      - "./transactional_agent_check.py:/opt/stackstate-agent/embedded/lib/python2.7/site-packages/stackstate_checks/base/checks/v2/transactional_agent_check.py"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
      - "/etc/passwd:/etc/passwd:ro"
      - "/sys/kernel/debug:/sys/kernel/debug"
    environment:
      STS_API_KEY: "API_KEY"
      STS_STS_URL: "http://host.docker.internal:7078/stsAgent"
      STS_PROCESS_AGENT_URL: "http://host.docker.internal:7078/stsAgent"
      STS_APM_URL: "http://host.docker.internal:7078/stsAgent"
      STS_PROCESS_AGENT_ENABLED: "true"
      STS_NETWORK_TRACING_ENABLED: "true"
      STS_APM_ENABLED: "true"
      HOST_PROC: "/host/proc"
      HOST_SYS: "/host/sys"
      STS_LOG_LEVEL: "debug"
      STS_LOG_TO_CONSOLE: "true"
      # STS_LOG_PAYLOADS: "true"

# Start Transaction
# Get State
# Get Transactional State
# - Run Check Logic
# Set State
# Set Transactional State
# Stop Transaction
